set_property SRC_FILE_INFO {cfile:C:/Users/junhao.zhang.freddie/Vivado_Projects/lab4/project_1/project_3/project_3.srcs/constrs_1/new/cons.xdc rfile:../../../project_3.srcs/constrs_1/new/cons.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN V17 [get_ports {I[0]}]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN V16 [get_ports {I[1]}]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN W16 [get_ports {I[2]}]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN V19 [get_ports {I[3]}]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN U16 [get_ports {Y[0]}]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN E19 [get_ports {Y[1]}]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN W13 [get_ports {Ein}]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN V14 [get_ports {Eout}]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN U14 [get_ports {GS}]
