set_property SRC_FILE_INFO {cfile:C:/Users/junhao.zhang.freddie/Vivado_Projects/lab4/project_1/project_1/project_1.srcs/constrs_1/new/cons.xdc rfile:../../../project_1.srcs/constrs_1/new/cons.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN V17 [get_ports {I0[0]}]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN V16 [get_ports {I0[1]}]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN W16 [get_ports {I1[0]}]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN W17 [get_ports {I1[1]}]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN W15 [get_ports {I2[0]}]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN V15 [get_ports {I2[1]}]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN W14 [get_ports {I3[0]}]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN W13 [get_ports {I3[1]}]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN W19 [get_ports {Sel[0]}]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN T17 [get_ports {Sel[1]}]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN U16 [get_ports {Y[0]}]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN E19 [get_ports {Y[1]}]
